services: 
    db: 
        image: mariadb:latest
        container_name: poe_mariadb
        restart: unless-stopped
        env_file: .env
        ports: 
            - 3306:3306
        volumes: 
            - ./datas:/var/lib/mysql
            - ./init.db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - cyber
    api: 
        image: webdevops/php-apache:8.2
        container_name: api_poe
        depends_on: 
            - db
        volumes: 
            - ./../php_api:/var/www/vhosts/api/htdocs
            - ./etc/apache2/api/sites-enabled:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        ports: 
            - 8003:80
        networks: 
            - cyber
    www:
        image: ubuntu/apache2:latest
        container_name: www_poe
        ports: 
            - 8080:80
        volumes:
            - ./../poe/dist:/var/www/vhosts/www/htdocs
            - ./etc/apache2/www/sites-enabled:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        depends_on:
            - api
        networks:
            - cyber
networks: 
    cyber: 
        driver: bridge
        external: false
